### ISSUE TITLE
Error with newer versions of Akka: java.lang.NoSuchMethodError: akka.http.scaladsl.server.RouteConcatenation

### ISSUE THREAD

**Issue by od0** [blstream/akka-viz#115]
Hey guys,

Thanks for the work on this project. It looks like there was a minor change to Akka's `RouteConcatenation` trait that causes this error:

```
[error] Uncaught error from thread [akka-viz-akka.actor.default-dispatcher-3] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[akka-viz]
[error] java.lang.NoSuchMethodError: akka.http.scaladsl.server.RouteConcatenation$class.enhanceRouteWithConcatenation(Lakka/http/scaladsl/server/RouteConcatenation;Lscala/Function1;)Lakka/http/scaladsl/server/RouteConcatenation$RouteWithConcatenation;
[error]     at akkaviz.server.Webservice.enhanceRouteWithConcatenation(Webservice.scala:19)
[error]     at akkaviz.server.Webservice$$anonfun$2.apply(Webservice.scala:24)
[error]     at akkaviz.server.Webservice$$anonfun$2.apply(Webservice.scala:30)
[error]     at akka.http.scaladsl.server.Directive$$anonfun$addByNameNullaryApply$1$$anonfun$apply$13.apply(Directive.scala:134)
```

Before:
https://github.com/akka/akka/blob/b3c85512a33d865a1d2ce98550df74d49790b059/akka-http/src/main/scala/akka/http/scaladsl/server/RouteConcatenation.scala#L20

After:
https://github.com/akka/akka/blob/master/akka-http/src/main/scala/akka/http/scaladsl/server/RouteConcatenation.scala#L20

`enhanceRouteWithConcatenation` was renamed to `_ enhanceRouteWithConcatenation`

It looks like this was built with Akka 2.4.2, before this change was made. It'd be great to get this working with the newer versions. I saw in another issue that you mentioned that people had moved on from this project, so I'm happy to take a stab at updating this.

**Comment by kra3** [comment]
Any progress or workaround for this?

**Comment by lustefaniak** [comment]
Current version is built for Akka 2.4.10, I guess it should work fine now.

śr., 21.09.2016, 18:02 użytkownik Arun Karunagath notifications@github.com
napisał:

**Comment by lustefaniak** [comment]
0.1.7, was released six days ago

**Comment by od0** [comment]
yes thank you for the update @lustefaniak, closing this out
